---

-hosts: all
 sudo: true
 tasks:
	name: update apt cache
	apt: update_cache=yes
	name: install nodejs
	apt: name=nodejs state=present
	name: install npm
	apt: name=npm state=present
	-npm: name=express state=absent global=yes
	-npm: name=mongodb state=absent global=yes

