---

- hosts: all
 sudo: true
 user: vagrant
 tasks:
 - name: update apt cache
   apt: update_cache=yes
 - name: install nodejs
   apt: name=nodejs state=present
 - name: install npm
   apt: name=npm state=present
 - name: install express
   npm: name=express global=yes
 - name: install mongo
   npm: name=mongodb global=yes

